### ISSUE TITLE
Remaining LATTICe-A annotated samples

### ISSUE THREAD

**Issue by bencheikhb1** [qalid7/compath#2]
Where can I find the remaining LATTICe-A annotated samples? You reported 26,960 cells annotated, but I could only find around 4,000 cells under **/latticea_test_data**

**Comment by qalid7** [comment]
Thank you for taking the interest @bencheikhb1 ! 

The reported 26,960 cells are from the TRACERx cohort. For any TRACERx related data, please refer to the 'Data availability' statement from the paper. 

The annotations available in this repository are from the 'external test' set (5,082 single-cells) and indeed from the LATTICe-A cohort.
